# Generated by Django 3.2.3 on 2021-06-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0003_auto_20210531_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=10),
        ),
    ]
