# Generated by Django 3.2.3 on 2021-06-01 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0004_pessoa_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('numero_sala', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='meuapp.departamento'),
        ),
    ]
