# Generated by Django 3.2.3 on 2021-06-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0005_auto_20210531_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(default=0)),
                ('numero', models.BigIntegerField(default=0)),
                ('temWhatsapp', models.BooleanField()),
            ],
        ),
    ]
