# Generated by Django 3.2.3 on 2021-06-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0006_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefones',
            field=models.ManyToManyField(to='meuapp.Telefone'),
        ),
    ]
