# Generated by Django 3.2.3 on 2021-07-04 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('classificacao', models.CharField(choices=[('D', 'Despesa'), ('R', 'Receita')], default='D', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('situacao', models.CharField(choices=[('N', 'a Receber'), ('S', 'Recebido')], default='N', max_length=10)),
                ('dataRecebimento', models.DateField()),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.classificacao')),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('situacao', models.CharField(choices=[('N', 'a Pagar'), ('S', 'Pago')], default='N', max_length=10)),
                ('formaPagamento', models.CharField(choices=[('D', 'Dinheiro'), ('CD', 'Débito'), ('CC', 'Crédito'), ('B', 'Boleto')], default='D', max_length=10)),
                ('validade', models.DateField(blank=True, null=True)),
                ('dataPagamento', models.DateField(blank=True, null=True)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.classificacao')),
            ],
        ),
    ]
